### PR TITLE
Use MVar in tryAny, drop async dependency

### PR DESCRIPTION
**Pull request by mitchellwrosen**
This was discussed a bit in https://github.com/snoyberg/yaml/issues/86

### CODE REVIEW

**Comment by snoyberg** [comment]
There's a (very) subtle issue with this, for which I've opened a PR:

https://github.com/mitchellwrosen/enclosed-exceptions/pull/1

Previous discussion:

https://github.com/simonmar/async/issues/14
https://github.com/simonmar/async/pull/15

**Comment by mitchellwrosen** [comment]
Right, I neglected to consider that particular async exception. That's fascinating. Very impressive that you spotted it just by reading the code!

**Comment by snoyberg** [comment]
I have a lot of experience in this particular failure case

**Comment by snoyberg** [comment]
@jcristovao I think this PR is good to go. Do you want to review/merge/release, or do you feel comfortable with me doing so?

**Comment by snoyberg** [comment]
I hope you don't mind @jcristovao, I've gone ahead with merging and releasing to Hackage.

**Comment by jcristovao** [comment]
Hi @snoyberg , sorry for the delay on this, I've been pretty busy at work. It looks great, thanks!

**Comment by snoyberg** [comment]
No problem, I definitely understand :)

**Pull request merged**
